#! /bin/bash

if [ `target/firesight -opencv` == "2.3" ]; then
  echo "OpenCV Test version: 2.3"
  ocvtest="-cv2.3"
else
  echo "OpenCV Test version: current"
  ocvtest=""
fi

echo ========== TEST lib_firesight.so =============
echo target/test 
target/test
if [ $? -ne 0 ] 
then 
	echo FAILED: target/test
	exit 1
fi

echo ========== TEST firesight =============
if [ `uname -m` == "x86_64" -o "$WINDIR" != "" ]; then suffix64="-64"; else suffix64="" ; fi
echo "Machine platform is:" `uname -m`
echo "Test suffix is:$suffix64"

suffix=""
test/test-one duck.jpg crop "$suffix" -Dx=50 -Dy=75 -Dwidth=100 -Dheight=50
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one duck.png warpAffine "-h$suffix" -Dreflect=[0,1]
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one duck.png warpAffine "-v$suffix" -Dreflect=[1,0]
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one cal-grid.png matchGrid-perspective "$suffix" -Dtemplate=img/cross32.png
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one cal-grid.png matchGrid "$suffix" -Dcalibrate=tile3 -Dtemplate=img/cross32.png
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one ass_place_phj.png MSER_phj2 "$suffix" 
if [ $? -ne 0 ] ; then exit 1 ; fi


suffix=""
test/test-one camera0724.png estimate-px-per-mm "$suffix" 
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one fiducial-cam1.jpg match-fiducial "-cam1$suffix" -Dtemplate=img/bwwb.jpg 
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one fiducial-cam2.jpg match-fiducial "-cam2$suffix" -Dtemplate=img/bwwb.jpg
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one w.png morph "-open-3$suffix" -Dmop=MORPH_OPEN -Dksize=3
if [ $? -ne 0 ]; then exit 1; fi
test/test-one w.png morph "-close-3$suffix" -Dmop=MORPH_CLOSE -Dksize=3
if [ $? -ne 0 ]; then exit 1; fi
test/test-one w.png morph "-dilate-3$suffix" -Dmop=MORPH_DILATE -Dksize=3
if [ $? -ne 0 ]; then exit 1; fi
test/test-one w.png morph "-erode-3$suffix" -Dmop=MORPH_ERODE -Dksize=3
if [ $? -ne 0 ]; then exit 1; fi
test/test-one w.png morph "-erode-5$suffix" -Dmop=MORPH_ERODE -Dksize=5
if [ $? -ne 0 ]; then exit 1; fi

suffix=""
test/test-one duck.jpg resize "$suffix" "-Dfx=0.25" "-Dfy=0.5"
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix="-64"
test/test-one pcb.png matchAngle "$suffix" "-Dangle=[45]" "-Dtemplate=img/tmplt-37x29.jpg"
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix="-64"
test/test-one pcb.png matchCCOEFF_NORMED "$suffix" 
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix="-64"
test/test-one pcb.png match45 "$suffix"
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one pcb.png absdiff "$suffix" "-Dimg=img/mog2.png" -ji 0
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one part1-0.png threshold "-otsu$suffix" 
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one absdiff.png threshold "64-color$suffix" "-Dthresh=64" "-Dgray=false"
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one absdiff.png threshold "64$suffix" "-Dthresh=64" 
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one absdiff.png threshold "64-inv$suffix" "-Dthresh=64" "-Dtype=THRESH_BINARY_INV"
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix="-64"
test/test-one whiterect.png dft-spectrum "$suffix" 
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix="$ocvtest"
test/test-one headcam1.png calcOffset "-1$suffix" -Dtemplate=img/headcam0.png
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one headcam0a.png calcOffset "-0a$suffix" -Dtemplate=img/headcam0.png
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one headcam0.png calcOffset "-offsetColor0$suffix" -Dtemplate=img/headcam0.png -Dchannels=[0,1,2] -DoffsetColor=[255,0,255]
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one headcam1.png calcOffset "-offsetColor1$suffix" -Dtemplate=img/headcam0.png -Dchannels=[0,1,2] -DoffsetColor=[255,0,255]
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one headcam2.png calcOffset "-1BGR$suffix" -Dtemplate=img/headcam0.png -Dchannels=[0,1,2]
if [ $? -ne 0 ] ; then exit 1 ; fi
suffix=""
test/test-one headcam1.png calcOffset "-1roi$suffix" -Dtemplate=img/headcam0.png -Droi=[380,75,35,35]
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one headcam1.png calcOffset "-2roi$suffix" -Dtemplate=img/headcam0.png -Droi=[-1,-1,50,50]
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix="-64"
test/test-one mog2.png bgsub "-mog2$suffix" "-DbgImg=img/pcb.png" "-Dmethod=MOG2"
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one mog2.png bgsub "-absdiff$suffix" "-DbgImg=img/pcb.png" "-Dmethod=absdiff" "-Dthresh=32"
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one duck.png putText "$suffix" -Dtext="Quirky Duck" "-Dcolor=[64,0,0]"
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one abc.png normalize "$suffix" 
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one abc.png normalize "-l1$suffix" -DnormType="NORM_L1"
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one abc.png normalize "-l2$suffix" -DnormType="NORM_L2" -Ddomain=[20,52]
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one abc.png normalize "-inf$suffix" -DnormType="NORM_INF" 
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one abc.png normalize "-minmax$suffix" -DnormType="NORM_MINMAX" 
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one abc-color.png minAreaRect "-abc$suffix" -Dchannel=1 -Dmin=128 -Dthickness=1
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one part1-0.png minAreaRect-thresh "$suffix" 
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one FireREST.png transparent "-fg$suffix" -Dalphafg=0.3 -Droi=[50,10,100,46]
if [ $? -ne 0 ] ; then exit 1 ; fi
test/test-one FireREST.png transparent "$suffix" -Dalphabg=0.7 -Dalphafg=.3 -Dbgcolor=[255,255,255] -Droi=[50,10,100,46]
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one duck.png model "$suffix" 
if [ $? -ne 0 ] ; then exit 1 ; fi

echo "-------------------------------------------------"
echo "BLISS AND HAPPINESS. FireSight TESTS ALL PASS!!!"
echo "-------------------------------------------------"
