#! /bin/bash

if [ `uname -m` == "x86_64" -o "$WINDIR" != "" ]; then suffix64="-win"; else suffix64="" ; fi
echo "Machine platform is:" `uname -m`
echo "Test suffix is:$suffix64"

suffix=$suffix64
test/test-one mog2.jpg mog2-fgMask "$suffix" "-DbgImg=img/pcb.jpg" 
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one duck.jpg resize "$suffix" "-Dfx=0.25" "-Dfy=0.5"
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=$suffix64
test/test-one pcb.jpg matchAngle "$suffix" "-Dangle=[45]" "-Dtemplate=img/tmplt-37x29.jpg"
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=$suffix64
test/test-one pcb.jpg matchCCOEFF_NORMED "$suffix" 
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=$suffix64
test/test-one pcb.jpg match45 "$suffix"
if [ $? -ne 0 ] ; then exit 1 ; fi

suffix=""
test/test-one pcb.jpg absdiff "$suffix" "-Dimg=img/mog2.jpg" 
if [ $? -ne 0 ] ; then exit 1 ; fi

echo ========== TEST lib_firesight.so =============
echo target/test 
target/test
if [ $? -ne 0 ] 
then 
	echo FAILED: target/test
	exit 1
fi

echo "---------------------------------------"
echo "BLISS AND HAPPINESS. FireSight TESTS ALL PASS!!!"
echo "---------------------------------------"
