#! /bin/bash

if [ ! -e /usr/bin/cmake ]
then
	echo "++++++++++++++++++ INSTALLING CMAKE ++++++++++++"
	apt-get -y install cmake
fi

if [ ! -e /usr/local/include/jansson.h ]
then
	echo "++++++++++++++++++ INSTALLING JANNSON C LIBRARY ++++++++++++"
	apt-get -y install dh-autoreconf
	git clone git://github.com/akheron/jansson ~pi/jannson
	pushd ~pi/jannson
	autoreconf -i
	./configure
	sudo -u $SUDO_USER cmake .
	make install
	popd
fi
if [ ! -e /usr/include/fuse.h ] 
then
	echo "++++++++++++++++++ INSTALLING FUSE C LIBRARIES ++++++++++++"
	apt-get -y install libfuse-dev
	ex -s -c "g/#user_allow_other/s/#//" -c wq /etc/fuse.conf
	cp firefuse.conf /etc/ld.so.conf.d/
	ldconfig
fi
if [ ! -e /usr/lib/libopencv_features2d.so ] 
then
	echo "++++++++++++++++++ INSTALLING OPENCV C++ LIBRARIES ++++++++++++"
	apt-get -y install libopencv-dev
fi

if [ -e CMakeFiles ] 
then 
	echo removing existing makefiles
	rm -rf CMakeCache.txt CMakeFiles CMakeFiles.txt target cmake_install.cmake CPackConfig.cmake CPackSourceConfig.cmake
	sudo -u $SUDO_USER mkdir target
fi


echo creating makefiles
sudo -u $SUDO_USER cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr "$@" .
echo building and installing FireSight...
make install

