#! /bin/bash

IMAGE=img/10x10grid.png
IMAGE=img/10x10grid-400.png
IMAGE=img/cal-grid.png
LOG=-info
LOG=-trace
OP=tile1
OP=tile5
OP=diamond
OP=ellipse
OP=corners
SCALE=[0.5,0.5]
SCALE=[0.6,0.6]
SCALE=[0.7,0.7]
SCALE=[0.8,0.8]
SCALE=[0.9,0.9]
SCALE=[1,1]
OP=tile4
OP=xyaxes
OP=cross
OP=none
OP=quad0
OP=quad3
OP=quad1
OP=tile2
OP=quad2
OP=tile3

make
if [ $? -eq 0 ]; then
	time target/firesight \
		-i $IMAGE \
		-p json/matchGrid.json \
		-o ~/Downloads/grid1.jpg \
		-Dtemplate=img/cross32.png \
		-Dcalibrate=$OP \
		-Dcorr=0.8 \
		-Dscale=$SCALE \
		$LOG \
		|& tee target/out
fi
