#! /bin/bash

IMAGE=img/10x10grid.png
IMAGE=img/10x10grid-400.png
IMAGE=img/cal-grid.png

LOG=-info
LOG=-trace

SCALE=-Dscale=[0.5,0.5]
SCALE=-Dscale=[0.6,0.6]
SCALE=-Dscale=[0.7,0.7]
SCALE=-Dscale=[0.8,0.8]
SCALE=-Dscale=[0.9,0.9]
SCALE=-Dscale=[1,1]

MATRIX=[1.0607967128675548,0.028493745902572951,-7.1703410533895173,0.026587775192913436,1.1255262314607453,-19.981908384664415,-1.3832327695678588e-5,0.00027923340765283015,1.0]
MATRIX=[1,0,0,0,1,0,0,0,1]

OP=diamond
OP=tile4
OP=xyaxes
OP=cross
OP=quad0
OP=quad3
OP=none
OP=quad1
OP=tile2
OP=ellipse
OP=corners
OP=tile3
OP=tile5
OP=quad2
OP=tile1
OP=perspective

TIME=time
TIME=

JSON=json/warpPerspective.json
JSON=json/matchGrid.json

OUTPUT=img/matchGrid-perspective.png
OUTPUT=~/Downloads/grid1.jpg

CORR=-Dcorr=0.8
CORR=

COLOR="-DcolorUndistort=[32,255,32] -DcolorMatch=[32,32,255]"

make
if [ $? -eq 0 ]; then
	$TIME target/firesight \
		-i $IMAGE \
		-p $JSON \
		-o $OUTPUT \
		-Dtemplate=img/cross32.png \
		-Dmatrix=$MATRIX \
		-Dcalibrate=$OP \
		$CORR \
		$SCALE \
		$LOG \
		$COLOR \
		|& tee target/out
fi
